description = "SPARK/Ada Algorithms Targeting Advanced Network Applications"
long-description = """Saatana - SPARK/Ada Algorithms Targeting Advanced Network Applications

A collection of cryptographic algorithms, proven for correctness in SPARK.

Currently contains [![Phelix](https://www.schneier.com/academic/archives/2005/01/phelix.html)](https://www.schneier.com/academic/archives/2005/01/phelix.html)
"""
name = "saatana"
version = "2.0.3"
licenses = ["WTFPL"]
website = "https://github.heisenbug.eu/Saatana"
authors = ["Vinzent \"Jellix\" Saranen"]
maintainers = ["vinzent@heisenbug.eu"]
maintainers-logins = ["Jellix"]
executables = ["test_phelix"]
project-files = ["saatana.gpr"]
tags = ["cryptography", "spark"]

[[depends-on]]
gnat = "^2020"
