name: Build Linux

on:
  push:
    paths-ignore:
    - 'LICENSE'
    - 'README.md'
    - '_config.yml'
    - 'artifacts/**'
    - 'doc/**'

jobs:
  build:
    name: CI on ${{ matrix.tag }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: # Those are alire's dockerhub alire/gnat:tag machines
          - centos-latest-community-2019
          - community-current
          - debian-stable
          - ubuntu-lts

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull alire/gnat:${{ matrix.tag }}
      - name: Build
        run: >
          docker run -v${PWD}:/security -w /security
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} .github/scripts/ci-build.sh
      - name: Run tests
        run: >
          docker run -v${PWD}:/security -w /security
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} .github/scripts/ci-test.sh
      - name: Commit and push test results to artifacts
        run: >
          .github/scripts/update_test_results.sh "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
