name: "Proof Linux"

on:
  schedule:
    # Run twice daily
    - cron: '42 0,12 * * *'

jobs:
  build:
    name: Proof on ${{ matrix.tag }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: # Those are alire's dockerhub alire/gnat:tag machines
          #- centos-community-2020
          - community-2020
        # SPARK is only available on community installation

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull alire/gnat:${{ matrix.tag }}
      - name: Build
        run: >
          docker run -v${PWD}:/saatana -w /saatana
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} .github/scripts/ci-build.sh
      - name: Proof
        run: >
          docker run -v${PWD}:/saatana -w /saatana
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} .github/scripts/ci-proof.sh
      - name: Commit and push prove logs to artifacts
        run: |
          cat _build/gnatprove/gnatprove.out > artifacts/gnatprove.out
          git config --local user.email "gh+saatana@heisenbug.eu"
          git config --local user.name "Auto Committer"
          git commit artifacts/gnatprove.out -m "* (Autocommit) Prove results."
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
      - name: Upload gnatprove stdout
        uses: actions/upload-artifact@master
        with:
          name: gnatprove-${{ matrix.tag }}.stdout
          path: gnatprove.stdout
      - name: TARing gnatprove output
        run: >
          tar --ignore-failed-read`(for i in "*.ali" "*.cswi" "*.stderr" "*.stdout"; do printf " --exclude=${i}"; done)` -vcf gnatprove-output.tar _build/gnatprove
      - name: Upload TAR archive of gnatprove output
        uses: actions/upload-artifact@master
        with:
          name: gnatprove-${{ matrix.tag }}-output.tar
          path: gnatprove-output.tar
      - name: Run tests
        run: >
          docker run -v${PWD}:/saatana -w /saatana
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} .github/scripts/ci-test.sh
      - name: Commit and push test results to artifacts
        run: >
          .github/scripts/update_test_results.sh "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
