name: Proof Linux

on:
  schedule:
    # Run twice daily
    - cron: '42 0,12 * * *'

jobs:
  build:
    name: Proof on ${{ matrix.tag }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: # Those are alire's dockerhub alire/gnat:tag machines
          - community-current
        # SPARK is only available on community installation

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull alire/gnat:${{ matrix.tag }}
      - name: Build
        run: >
          docker run -v${PWD}:/security -w /security
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash .github/scripts/ci-build.sh
      - name: Proof
        run: >
          docker run -v${PWD}:/security -w /security
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash .github/scripts/ci-proof.sh
      #- name: Upload provelogs
      #  uses: actions/upload-artifact@master
      #  with:
      #    name: gnatprove-${{ matrix.tag }}.out
      #    path: _build/gnatprove/gnatprove.out
      - name: Commit and push prove logs to artifacts
        run: >
            cat _build/gnatprove/gnatprove.out > artifacts/gnatprove.out
            echo "\nProof run from `date --iso-8601=minutes`." >> artifacts/gnatprove.out # add timestamp to force changes
            git config --local user.email "gh+saatana@heisenbug.eu"
            git config --local user.name "Auto Committer"
            git commit artifacts/gnatprove.out -m "* (Autocommit) Prove results."
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
      - name: Upload gnatprove stdout
        uses: actions/upload-artifact@master
        with:
          name: gnatprove-${{ matrix.tag }}.stdout
          path: gnatprove.stdout
      - name: Known Answers Test
        run: >
          docker run -v${PWD}:/security -w /security
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash .github/scripts/ci-test.sh
      #- name: Upload KAT results
      #  uses: actions/upload-artifact@master
      #  with:
      #    name: kat-${{ matrix.tag }}.out
      #    path: kat.out
      - name: Commit and push KAT results to artifacts
        run: >
          cat kat.out > artifacts/test_results.out
          echo "\nTest run from `date --iso-8601=minutes`." >> artifacts/test_results.out # add timestamp to force changes
          git config --local user.email "gh+saatana@heisenbug.eu"
          git config --local user.name "Auto Committer"
          git commit artifacts/test_results.out -m "* (Autocommit) Test results."
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
