name: Proof on Linux

on:
  schedule:
    -cron: '0 * * * *' # hourly seems a bit overkill, but we need to test it...

jobs:
  build:
    name: Proof on ${{ matrix.tag }}
    runs-on: ubuntu-latest
    needs: 'Build on Linux'

    strategy:
      matrix:
        tag: # Those are alire's dockerhub alire/gnat:tag machines
          - community-current
        # SPARK is only available on community installation

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull alire/gnat:${{ matrix.tag }}
      - name: Build
        run: >
          docker run -v${PWD}:/security -w /security
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash scripts/ci-build.sh
      - name: Proof
        run: >
          docker run -v${PWD}:/security -w /security
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash scripts/ci-proof.sh
      - name: Upload provelogs
        uses: actions/upload-artifact@master
        with:
          name: gnatprove-${{ matrix.tag }}.out
          path: _build/gnatprove/gnatprove.out
      - name: Upload gnatprove stdout
        uses: actions/upload-artifact@master
        with:
          name: gnatprove-${{ matrix.tag }}.stdout
          path: gnatprove.stdout
      - name: Known Answers Test
        run: >
          docker run -v${PWD}:/security -w /security
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash scripts/ci-test.sh
      - name: Upload KAT results
        uses: actions/upload-artifact@master
        with:
          name: kat-${{ matrix.tag }}.out
          path: kat.out
